from __future__ import annotations

import json
import re
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field


class AgentDecision(BaseModel):
    """Structured decision produced by the Agent at each iteration of the loop."""

    thought: Optional[str] = Field(
        default=None,
        description="Brief reasoning about what information is known and what step to take next.",
    )
    action: Literal["tool", "final", "refuse"] = Field(
        ...,
        description="The action type: 'tool' to execute an MCP tool, 'final' when ready to answer, 'refuse' if question is out-of-scope.",
    )
    tool_name: Optional[str] = Field(
        default=None,
        description="Name of the MCP tool to execute if action is 'tool'.",
    )
    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments passed to the chosen tool.",
    )
    answer: Optional[str] = Field(
        default=None,
        description="The final comprehensive answer if action is 'final'.",
    )
    reason: Optional[str] = Field(
        default=None,
        description="Explanation if action is 'refuse'.",
    )

    @classmethod
    def parse_from_llm_output(cls, raw_output: str) -> "AgentDecision":
        """
        Robustly parse an AgentDecision from raw LLM output.
        Handles markdown code fences, leading text, or malformed JSON.
        """
        text = raw_output.strip()

        # 1. Strip markdown fences if present
        if "```" in text:
            fence_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
            if fence_match:
                text = fence_match.group(1).strip()
            else:
                text = re.sub(r"^```(?:json)?", "", text).strip()
                text = re.sub(r"```$", "", text).strip()

        # 2. Extract first matching outer JSON object
        if not text.startswith("{"):
            json_match = re.search(r"(\{.*\})", text, re.DOTALL)
            if json_match:
                text = json_match.group(1)

        try:
            data = json.loads(text)
        except Exception:
            # Fallback heuristic: check if raw text looks like a final answer or tool call
            lower = raw_output.lower()
            if any(k in lower for k in ["schema", "columns", "types", "get_table_schema"]):
                table = "employees" if "employee" in lower else ("orders" if "order" in lower else ("customers" if "customer" in lower else "unknown"))
                return cls(
                    thought="Fallback parsed tool request for schema.",
                    action="tool",
                    tool_name="get_table_schema",
                    arguments={"table_name": table},
                )
            elif any(k in lower for k in ["count", "rows", "how many", "get_table_row_count"]):
                table = "employees" if "employee" in lower else ("orders" if "order" in lower else ("customers" if "customer" in lower else "unknown"))
                return cls(
                    thought="Fallback parsed tool request for row count.",
                    action="tool",
                    tool_name="get_table_row_count",
                    arguments={"table_name": table},
                )
            elif any(k in lower for k in ["sample", "example", "show me", "get_table_sample"]):
                table = "employees" if "employee" in lower else ("orders" if "order" in lower else ("customers" if "customer" in lower else "unknown"))
                return cls(
                    thought="Fallback parsed tool request for sample.",
                    action="tool",
                    tool_name="get_table_sample",
                    arguments={"table_name": table, "limit": 3},
                )
            else:
                # Treat raw text as final answer if model spoke naturally
                return cls(
                    thought="Direct answer generated by model.",
                    action="final",
                    answer=raw_output.strip(),
                )

        # Normalize action field
        action_val = str(data.get("action", "")).strip().lower()
        if action_val not in ("tool", "final", "refuse"):
            if data.get("tool_name"):
                action_val = "tool"
            elif data.get("answer"):
                action_val = "final"
            elif data.get("reason"):
                action_val = "refuse"
            else:
                action_val = "final"
                data["answer"] = raw_output.strip()

        tool_name = data.get("tool_name")
        if action_val != "tool":
            tool_name = None
        elif tool_name:
            tool_name = str(tool_name).strip()

        args = data.get("arguments", {})
        if not isinstance(args, dict):
            args = {}

        raw_ans = data.get("answer")
        if isinstance(raw_ans, (dict, list)):
            final_ans_str = json.dumps(raw_ans, indent=2)
        elif raw_ans is not None:
            final_ans_str = str(raw_ans).strip()
        else:
            final_ans_str = None

        raw_reason = data.get("reason")
        if isinstance(raw_reason, (dict, list)):
            reason_str = json.dumps(raw_reason, indent=2)
        elif raw_reason is not None:
            reason_str = str(raw_reason).strip()
        else:
            reason_str = None

        return cls(
            thought=data.get("thought"),
            action=action_val,  # type: ignore
            tool_name=tool_name,
            arguments=args,
            answer=final_ans_str,
            reason=reason_str,
        )


class AgentStep(BaseModel):
    """Represents a single executed step within the agentic workflow."""

    step_number: int
    thought: Optional[str] = None
    action: str
    tool_name: Optional[str] = None
    arguments: dict[str, Any] = Field(default_factory=dict)
    tool_result: Optional[dict[str, Any]] = None
    observation_summary: Optional[str] = None
    answer: Optional[str] = None
    latency_seconds: float = 0.0


class AgentState(BaseModel):
    """Execution state tracking the agent's multi-step investigation."""

    question: str
    steps: list[AgentStep] = Field(default_factory=list)
    status: str = "in_progress"
    final_answer: Optional[str] = None
    total_latency_seconds: float = 0.0

    def add_step(self, step: AgentStep) -> None:
        self.steps.append(step)

    def format_history_for_prompt(self) -> str:
        """Render the sequence of steps and observations into a prompt-friendly text."""
        if not self.steps:
            return "No previous steps executed yet."

        history_lines = []
        for s in self.steps:
            if s.action == "tool":
                obs = json.dumps(s.tool_result) if s.tool_result else s.observation_summary or "None"
                history_lines.append(
                    f"Step {s.step_number}: Executed '{s.tool_name}' with args {json.dumps(s.arguments)}\n"
                    f"Observation: {obs}"
                )
            elif s.action == "final":
                history_lines.append(f"Step {s.step_number}: Final answer provided.")
            elif s.action == "refuse":
                history_lines.append(f"Step {s.step_number}: Refused with reason: {s.observation_summary}")

        return "\n\n".join(history_lines)
